FROM debian:jessie

MAINTAINER info@tango-controls.org

ARG TANGO_LIB_VER

ARG TANGO_SOURCE_DISTRIBUTION_VER

RUN apt-get update && apt-get install -y build-essential omniidl libomniorb4-dev libcos4-dev libomnithread3-dev libzmq3-dev mysql-client libmysqlclient-dev